apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tekton-ci-pipelines
  title: Tekton Pipelines in pipelines namespace
  annotations:
    janus-idp.io/tekton: 'true'
    backstage.io/kubernetes-namespace: pipelines
    backstage.io/kubernetes-id: tekton-ci-pipelines 
spec:
  type: namespace
  owner: oteemo-team 

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: oteemo-team
  description: Oteemo DevOps Team
spec:
  type: team
  profile:
    displayName: Oteemo Team
  children: []
